import { RuralEventCategoryList } from "./rural-event-category.types";

/**
 * The list of all rural event categories incl. localizations.
 */
export const ruralEventCategories: RuralEventCategoryList = [
  {
    id: "community-life",
    localizations: [
      {
        locale: "de",
        short: "Gemeindeleben",
        name: "Gemeinde & Freizeit & Sport",
        examples: [
          "Gemeindevertretungen",
          "Ausschüsse",
          "Amt",
          "Kirchenrat",
          "Vereinstreffen",
          "Stammtisch",
          "Feuerwehr",
          "Sporttraining",
        ],
      },
      {
        locale: "en",
        short: "Community Life",
        name: "Community & Leisure & Sport",
        examples: [
          "Community Council",
          "Committees",
          "Office",
          "Church Council",
          "Club Meetings",
          "Regulars",
          "Fire Department",
          "Sports Training",
        ],
      },
      {
        locale: "pl",
        short: "Życie społeczności",
        name: "Społeczność & Wypoczynek & Sport",
        examples: [
          "Rada Społeczności",
          "Komisje",
          "Biuro",
          "Rada Kościoła",
          "Spotkania Klubowe",
          "Stali Klienci",
          "Straż Pożarna",
          "Trening Sportowy",
        ],
      },
    ],
  },
  {
    id: "education-health",
    localizations: [
      {
        locale: "de",
        short: "Bildung & Gesundheit",
        name: "Beruf & Bildung & Gesundheit",
        examples: [
          "Volkshochschule",
          "Arbeitsamt",
          "Bibliotheken",
          "Arztpaxis",
          "Fußpflege",
          "Kinderbetreuung",
          "Impfzentrum",
        ],
      },
      {
        locale: "en",
        short: "Education & Health",
        name: "Job & Education & Health",
        examples: [
          "Adult Education",
          "Job Center",
          "Libraries",
          "Doctor's Office",
          "Foot Care",
          "Child Care",
          "Vaccination Center",
        ],
      },
      {
        locale: "pl",
        short: "Edukacja & Zdrowie",
        name: "Praca & Edukacja & Zdrowie",
        examples: ["Dorośli", "Centrum Pracy", "Biblioteki"],
      },
    ],
  },
  {
    id: "everyday-supply",
    localizations: [
      {
        locale: "de",
        short: "Versorgung",
        name: "Versorgung & Einkaufen & Verkehr",
        examples: [
          "Bus",
          "Bahn",
          "Fähre",
          "Brücke",
          "Rufbus",
          "Müll",
          "Bäcker",
          "Fleischer",
          "Supermärkte",
          "Hofläden",
        ],
      },
      {
        locale: "en",
        short: "Everyday Supply",
        name: "Supply & Shopping & Traffic",
        examples: [
          "Bus",
          "Train",
          "Ferry",
          "Bridge",
          "Call Bus",
          "Trash",
          "Bakery",
          "Butcher",
          "Supermarkets",
          "Farm Shops",
        ],
      },
      {
        locale: "pl",
        short: "Zaspokojenie codziennych potrzeb",
        name: "Zaspokojenie codziennych potrzeb & Zakupy & Ruch drogowy",
        examples: [
          "Autobus",
          "Pociąg",
          "Prom",
          "Most",
          "Autobus",
          "Śmieci",
          "Piekarz",
        ],
      },
    ],
  },
  {
    id: "culture-tourism",
    localizations: [
      {
        locale: "de",
        short: "Kultur & Touruismus",
        name: "Kultur & Touruismus & Veranstaltungen",
        examples: [
          "Konzerte",
          "Ausstellungen",
          "Musseen",
          "Kino",
          "Adlertouren",
          "Försterführungen",
          "Restaurants",
          "Cafes",
        ],
      },
      {
        locale: "en",
        short: "Culture & Tourism",
        name: "Culture & Tourism & Events",
        examples: [
          "Concerts",
          "Exhibitions",
          "Museums",
          "Cinema",
          "Eagle Tours",
          "Forester Tours",
          "Restaurants",
          "Cafes",
        ],
      },
      {
        locale: "pl",
        short: "Kultura & Turystyka",
        name: "Kultura & Turystyka & Wydarzenia",
        examples: [
          "Koncerty",
          "Wystawy",
          "Muzea",
          "Kino",
          "Kawiarnie",
          "Wycieczki z orłem",
          "Wycieczki z leśnikiem",
          "Restauracje",
        ],
      },
    ],
  },
];
