import { z } from "zod";
import { OccurrenceSchema } from "./occurrence.types";
import { RuralEventScope } from "@/packages/rural-event-types/src/rural-event-scope.types";
import { GeonameIdSchema } from "./geonames.types";

export const IndexedEventSchema = z.object({
  id: z.string().optional(),
  "summary.de": z.string(),
  "summary.en": z.string(),
  "summary.pl": z.string(),
  "summary.uk": z.string(),
  "summary.ru": z.string(),
  "description.de": z.string(),
  "description.en": z.string(),
  "description.pl": z.string(),
  "description.uk": z.string(),
  "description.ru": z.string(),
  link: z.string(),
  image: z.string(),
  "image.exists": z.boolean(),
  document: z.string(),
  "document.exists": z.boolean(),
  categories: z.array(z.string()),
  tags: z.array(z.string()),
  start: z.number(),
  end: z.number(),
  allday: z.boolean(),
  occurrence: OccurrenceSchema,
  "series.id": z.string(),
  "location.raw": z.string(),
  "location.name.de": z.string(),
  "location.localname.de": z.string(),
  "location.address": z.string(),
  "location.geopoint": z.any(),
  scope: RuralEventScope,
  "community.id": GeonameIdSchema,
  "community.geopoint": z.any(),
  "community.name.de": z.string(),
  "municipality.id": GeonameIdSchema,
  "municipality.name.de": z.string(),
  "county.id": GeonameIdSchema,
  "county.name.de": z.string(),
  "state.id": GeonameIdSchema,
  "state.name.de": z.string(),
  "country.id": z.string(),
  "country.name.de": z.string(),
  "organizer.id": z.string(),
  "organizer.name": z.string(),
  "calendar.id": z.string(),
  "calendar.name": z.string(),
  created: z.number(),
  changed: z.number(),
  deleted: z.number(),
});
export type IndexedEvent = z.infer<typeof IndexedEventSchema>;
